# Generated by Django 3.0.5 on 2020-04-17 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200417_0004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='music',
            table='music',
        ),
    ]
